
# uv.tip.racer.comunits1=<color=255,255,0>Jednostki Dowodzące</color> nie mogą się naprawiać ani u Mechaników ani zestawami naprawczymi.

# uv.tip.racer.comunits3=Nie możesz zgubić glin jeśli mają <color=255,255,0>Dowódcę</color> - najpierw się go pozbądź!

# uv.tip.racer.disorient=Skręcaj ostro i nagle lub skacz nad wodą żeby zdezorientować Jednostki.

# uv.tip.unit.pt.ghost1=Podejrzani używający [string:uv.ptech.ghost] dalej są podatni na [string:uv.ptech.emp], [string:uv.ptech.killswitch] i [string:uv.ptech.shockram].

