
# uv.tip.racer.comunits1=Las <color=255,255,0>Unidades Comandante</color> no reaparecen con kits de reparación, y no pueden reparase en las estaciones de reparación.

# uv.tip.racer.comunits3=No puedes evadir si hay una <color=255,255,0>Unidad Comandante</color> circulando - ¡Primero derribala!

# uv.tip.racer.disorient=Toma curvas verradas, finas, repentinas o salta sobre el agua para desorientar a las unidades.

# uv.tip.unit.pt.ghost1=Los sospechososque hagan uso del [string:uv.ptech.ghost] pueden seguir siendo impactados por el [string:uv.ptech.emp], [string:uv.ptech.killswitch] y el [string:uv.ptech.shockram].

