
# uv.tip.racer.comunits1=<color=255,255,0>Командиры</color> не появляются с ремкомплектами и не могут починиться в Мастерской.

# uv.tip.racer.comunits3=Ты не сможешь сбежать, если есть <color=255,255,0>Командир</color> рядом - сначала выведи его из строя!

# uv.tip.racer.disorient=Делай резки, неожиданные повороты или прыгай через воду, чтобы дезориентировать Юнитов.

# uv.tip.unit.pt.ghost1=Подозреваемые, использующие [string:uv.ptech.ghost], могут также получать урон от [string:uv.ptech.emp], [string:uv.ptech.killswitch] и [string:uv.ptech.shockram].

